import logging
import os
from datetime import datetime


LOG_FILE=f"{datetime.now().strftime('%m_%d_%Y_%H_%M_%S')}.log"
log_path=os.path.join(os.getcwd(),"logs",LOG_FILE)
os.makedirs(log_path,exist_ok=True)


LOG_FILE_PATH= os.path.join(log_path,LOG_FILE)

logging.basicConfig(
    filename=LOG_FILE_PATH,
    format="[ %(asctime)s ] %(lineno)d %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)


##   This code sets up a logging system in Python.It creates a log file with a name based on the current date and time, creates a directory named "logs" to store log files if it doesn't exist, configures the logging system to write log messages to the specified log file, and sets the log level to INFO. With this setup, any subsequent log messages generated by the application will be written to the log file in the specified format
